import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./common/Header";
import Footer from "./common/Footer";
import 'izitoast/dist/css/iziToast.min.css'; // <-- Import iziToast CSS here
import ReduxProvider from "./redux/provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="pt[180px]">
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
        </body>
    </html>
  );
}
